# Generated by Django 4.2.16 on 2024-09-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_short_name', models.CharField(max_length=100, verbose_name='نام کوتاه سازمان')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='نام سازمان')),
                ('api_enabled', models.BooleanField(blank=True, default=False)),
                ('limit_user', models.IntegerField(verbose_name='تعداد کاربر مجاز')),
                ('expired_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('latest_check', models.DateTimeField(auto_now_add=True, verbose_name='آخرین چک')),
            ],
            options={
                'verbose_name': 'لایسنس',
                'verbose_name_plural': 'لایسنس سامانه',
            },
        ),
        migrations.CreateModel(
            name='WinServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='server', max_length=255, unique=True, verbose_name='نام سرور')),
                ('ip', models.CharField(default='123.456.789.123', max_length=25, verbose_name='آدرس سرور')),
                ('port', models.CharField(default='636', max_length=25, verbose_name='پورت سرور')),
                ('proxy_user', models.CharField(default='admin', max_length=25, verbose_name='نام کاربری')),
                ('proxy_password', models.CharField(default='changeme', max_length=25, verbose_name='کلمه عبور')),
                ('ldap_domain', models.CharField(blank=True, default='example.local', max_length=25, verbose_name='دامنه')),
                ('description', models.TextField(blank=True, default='test', verbose_name='توضیحات ')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_ldap', models.BooleanField(default=False, verbose_name='LDAP')),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=100, verbose_name='تاریخ ایجاد سرور')),
                ('updated_at', models.DateTimeField(auto_now=True, max_length=100, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'سرور ',
                'verbose_name_plural': 'مشخصات سرور',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekdays', models.CharField(help_text="Comma-separated list of weekdays (e.g., '0,1,2,3,4' for Monday to Friday)", max_length=13)),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعت کاری سامانه',
            },
        ),
    ]
