# Generated by Django 4.2.16 on 2024-09-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WinServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='server', max_length=255, unique=True, verbose_name='نام سرور')),
                ('ip', models.CharField(default='123.456.789.123', max_length=25, verbose_name='آدرس سرور')),
                ('port', models.CharField(default='636', max_length=25, verbose_name='پورت سرور')),
                ('proxy_user', models.CharField(default='admin', max_length=25, verbose_name='نام کاربری')),
                ('proxy_password', models.CharField(default='changeme', max_length=25, verbose_name='کلمه عبور')),
                ('ldap_domain', models.CharField(blank=True, default='example.local', max_length=25, verbose_name='دامنه')),
                ('description', models.TextField(blank=True, default='test', verbose_name='توضیحات ')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_ldap', models.BooleanField(default=False, verbose_name='LDAP')),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=100, verbose_name='تاریخ ایجاد سرور')),
                ('updated_at', models.DateTimeField(auto_now=True, max_length=100, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'سرور ',
                'verbose_name_plural': 'مشخصات سرور',
            },
        ),
    ]
