# Generated by Django 4.2.16 on 2024-09-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_short_name', models.CharField(max_length=100, verbose_name='نام کوتاه سازمان')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='نام سازمان')),
                ('api_enabled', models.BooleanField(blank=True, default=False)),
                ('limit_user', models.IntegerField(verbose_name='تعداد کاربر مجاز')),
                ('expired_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('latest_check', models.DateTimeField(auto_now_add=True, verbose_name='آخرین چک')),
            ],
            options={
                'verbose_name': 'مشخصات ',
                'verbose_name_plural': 'مشخصات سامانه',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekdays', models.CharField(help_text="Comma-separated list of weekdays (e.g., '0,1,2,3,4' for Monday to Friday)", max_length=13)),
            ],
        ),
    ]
