# Generated by Django 4.2.16 on 2024-09-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwm', '0002_licenseinfo_workinghours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenseinfo',
            options={'verbose_name': 'لایسنس', 'verbose_name_plural': 'لایسنس سامانه'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name': 'ساعت کاری', 'verbose_name_plural': 'ساعت کاری سامانه'},
        ),
    ]
